### ISSUE TITLE
Not working for 1.5

### ISSUE THREAD

**Issue by NicciBG** [bbradson/Xenotype-Spawn-Control#2]
Unfortunately the mod don't work with v 1.5.

Also there are some inconsistencies with the default settings - Toxers for example are set to 100% baseline. Same with Yttakins and some other.

**Comment by bbradson** [comment]
Cannot reproduce. The mod works fine on my end, nothing related to it changed in the whole 1 method it has a harmony patch on.
Settings fetch their data from vanilla values as set in RimWorld\Data\Biotech\Defs\FactionDefs for example. The mod does not automatically make changes to them and does not contain any code for default values to replace them with
